version: "3.9"
services:
  itgenuine-container:
    image: robystunna2/itgenius
    container_name: itgenius
    ports:
      - "8085:8085"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: itgeniusdb
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

